Build a search request: https://www.earthdatascience.org/courses/use-data-open-source-python/intro-to-apis/twitter-data-in-python/

In [3]:
import requests
import os
import tweepy as tw
import pandas as pd
from keys import consumer_key, consumer_secret, access_token, access_token_secret

In [19]:
auth = tw.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tw.API(auth, wait_on_rate_limit=True)

In [6]:
search_words = "#vaccine" + "-filter:retweets"
date_since = "2021-01-01"

In [7]:
chi_tweets = tw.Cursor(api.search,
                       q=search_words,
                       lang="en",
                       since=date_since,
                       geocode="41.881832,-87.623177,20km",
                       tweet_mode='extended'
                  ).items()

In [7]:
hou_tweets = tw.Cursor(api.search,
                       q=search_words,
                       lang="en",
                       since=date_since,
                       geocode="29.749907,-95.358421,20km"
                  ).items()

In [14]:
ny_tweets = tw.Cursor(api.search,
                       q=search_words,
                       lang="en",
                       since=date_since,
                       geocode="40.730610,-73.935242,20km"
                  ).items()

In [20]:
la_tweets = tw.Cursor(api.search,
                       q=search_words,
                       lang="en",
                       since=date_since,
                       geocode="34.052235,-118.243683,20km",
                       tweet_mode="extended"
                       ).items()

Help with last function

https://towardsdatascience.com/my-first-twitter-app-1115a327349e

In [70]:
# trends_result = api.trends_place(1)
# for trend in trends_result[0]["trends"]:
#     print(trend["name"])

In [21]:
# fuction to extract data from tweet object
def extract_tweet_attributes(tweet_object):
    # create empty list
    tweet_list =[]
    # loop through tweet objects
    for tweet in tweet_object:
        tweet_id = tweet.id # unique integer identifier for tweet
        text = tweet.full_text # utf-8 text of tweet
        favorite_count = tweet.favorite_count
        retweet_count = tweet.retweet_count
        created_at = tweet.created_at # utc time tweet created
        source = tweet.source # utility used to post tweet
        reply_to_status = tweet.in_reply_to_status_id # if reply int of orginal tweet id
        reply_to_user = tweet.in_reply_to_screen_name # if reply original tweetes screenname
        retweets = tweet.retweet_count # number of times this tweet retweeted
        favorites = tweet.favorite_count # number of time this tweet liked
        location = tweet.user.location
        # append attributes to list
        tweet_list.append({'tweet_id':tweet_id, 
                          'text':text, 
                          'favorite_count':favorite_count,
                          'retweet_count':retweet_count,
                          'created_at':created_at, 
                          'source':source, 
                          'reply_to_status':reply_to_status, 
                          'retweets':retweets,
                          'favorites':favorites,
                          'location': location})
    # create dataframe   
    df = pd.DataFrame(tweet_list, columns=['tweet_id',
                                           'text',
                                           'favorite_count',
                                           'retweet_count',
                                           'created_at',
                                           'source',
                                           'reply_to_status',
                                           'retweets',
                                           'favorites',
                                           'location'])
    return df

In [18]:
chi_df = extract_tweet_attributes(chi_tweets)
chi_df

Empty DataFrame
Columns: [tweet_id, text, favorite_count, retweet_count, created_at, source, reply_to_status, retweets, favorites, location]
Index: []

In [15]:
hou_df = extract_tweet_attributes(hou_tweets)
hou_df

Empty DataFrame
Columns: [tweet_id, text, favorite_count, retweet_count, created_at, source, reply_to_status, retweets, favorites, location]
Index: []

https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html

In [15]:
ny_df = extract_tweet_attributes(ny_tweets)
ny_df

,tweet_id,text,favorite_count,retweet_count,created_at,source,reply_to_status,retweets,favorites,location
0,1406361252134363136,Please get a #vaccine. https://t.co/VS2S3qzV9n,0,0,2021-06-19 21:20:26,Twitter Web App,NaN,0,0,"New York, USA"
1,1406303796968427524,The @HHS.gov #COVID19 public education campaig...,0,0,2021-06-19 17:32:07,Sendible,NaN,0,0,New York
2,1406303725396893696,"Man sues 7 airlines including JetBlue, Southwe...",0,0,2021-06-19 17:31:50,Twitter Web App,NaN,0,0,"New York, NY"
3,1406287192314499080,Pediatric infectious disease specialist at the...,4,0,2021-06-19 16:26:08,Twitter for iPhone,NaN,0,4,"Bronx, NY"
4,1406272081805950982,@moderna_tx seeks #COVID-19 #vaccine authoriza...,0,0,2021-06-19 15:26:06,Sprout Social,NaN,0,0,New York
...,...,...,...,...,...,...,...,...,...,...
301,1403375844068925445,"#CovidVaccine is a global public good, there i...",0,0,2021-06-11 15:37:29,Twitter Web App,NaN,0,0,"New York, USA"
302,1403373962613100555,Moderna Files for Emergency Use Authorization ...,2,0,2021-06-11 15:30:00,Twitter Web App,NaN,0,2,"New York, NY"
303,1403366504549257220,The USA vaccine pace is slowing. \n\nhttps://t...,0,0,2021-06-11 15:00:22,Hootsuite Inc.,NaN,0,0,"New York, NY"
304,1403365536172580869,THEY (Government) LYIN'!!!!! The man who prove...,0,0,2021-06-11 14:56:31,Twitter for Android,NaN,0,0,"New York, NY"
305,1403363909717966857,Looking forward to @IAmBiotech conference next...,0,0,2021-06-11 14:50:03,Sprout Social,NaN,0,0,"New York, USA"

In [22]:
la_df = extract_tweet_attributes(la_tweets)
la_df

,tweet_id,text,favorite_count,retweet_count,created_at,source,reply_to_status,retweets,favorites,location
0,1406359961190363139,@fitterhappierAJ @DeannaMarie208 @SapnaKmd @VS...,2,0,2021-06-19 21:15:18,Twitter Web App,1.406360e+18,0,2,"Los Angeles, CA"
1,1406336817415131140,The cold hard truth burned through your soul &...,0,0,2021-06-19 19:43:20,Twitter Web App,NaN,0,0,Los Angeles
2,1406319497351467012,Y does everyone act like if u don't have the j...,0,0,2021-06-19 18:34:30,Twitter for Android,NaN,0,0,"West Hollywood, CA"
3,1406132119445835779,#pfizer #covid #vaccine \nLet's salute the gol...,0,0,2021-06-19 06:09:56,Twitter for Android,NaN,0,0,90210
4,1406121032491143171,Rio Grande Valley Latina has helped hundreds a...,0,0,2021-06-19 05:25:53,SocialRabbit Plugin,NaN,0,0,"Los Angeles, CA"
...,...,...,...,...,...,...,...,...,...,...
102,1403445752345501698,The same organization that made this ridiculou...,0,0,2021-06-11 20:15:16,Twitter for iPhone,NaN,0,0,"Los Angeles, CA"
103,1403443166691397643,To double down on their commitment to a safe r...,0,0,2021-06-11 20:05:00,Twitter for Advertisers,NaN,0,0,"Los Angeles, CA"
104,1403436992839389184,HUGE thanks to the doctors administering vacci...,1,0,2021-06-11 19:40:28,Twitter Web App,NaN,0,1,"Los Angeles, CA"
105,1403414354343591936,Here's your #RecipeOfTheDay for good health......,0,0,2021-06-11 18:10:30,Twitter Web App,NaN,0,0,County of Los Angeles
106,1403409804299845635,Migos #Vaccine is the record,1,0,2021-06-11 17:52:26,Twitter Web App,NaN,0,1,Atl & LA

In [24]:
pd.set_option('display.max_colwidth', -1)
la_df.iloc[3]['text']

"#pfizer #covid #vaccine \nLet's salute the golden oldies who took the shot https://t.co/TvlB9th4ir"

In [25]:
la_df.to_csv('test.csv')